### ISSUE TITLE
Code not executing because of indentation issues.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#15]
**Commit Hash:** 6c5c3d040905536aa119bb7e48a96b76261721fc

### Description
There are few functions in which indentations are given using both spaces
and tabs. For this reason, the programs are not executing. It is advised that developers
should run the program and test it after every major commit. If the program is not running
then you should mention it in the commit message.

All the errors are in the file `wave_equation.py`.

**Comment by Balavarun5** [comment]
I'll fix this issue and send a PR from this branch.

**Comment by amanabt** [comment]
close this issue after fixing the issue.

**Comment by Balavarun5** [comment]
Updated the code and sent a PR from 'lax_friedrichs_flux' branch

**Comment by mchandra** [comment]
@Balavarun5 close the issue when the PR is merged.

**Comment by Balavarun5** [comment]
The PR has been merged and the code is executing
