### ISSUE TITLE
Usage of global variables in the code.

### ISSUE THREAD

**Issue by Balavarun5** [QuazarTech/DG_Maxwell#17]
#### Description
Global variables are used in the code (all of them in `global_variables.py`). The usage of global variables can be avoided in the code.

#### Motivation
While global variables are not detrimental to the code, It is not a good coding practice to use them.

#### Possible implementation
[Edited] A version of the code which doesn't use global variables needs to be developed.

**Comment by amanabt** [comment]
@Balavarun5 
You say PR #16 is not using global variables. But, I checked that PR and I found that
the global variables are still being used. Your claim is very misleading. What's going on?

**Comment by Balavarun5** [comment]
The keyword `global` which was used to declare global variables was removed from the module `global_variables.py` .

A variable initialized using the `global` keyword can be accessed anywhere within the code (eg : A new function declared elsewhere in the module can use these variables.).

The new implementation is to declare these variables in the module itself without the help of a function.
These variables can't be referenced inside a function elsewhere (i.e.- A new function declared elsewhere in the module cannot use these variables).

When it was said that global  variables were removed I was referring to declaring these variables using a **global** keyword within a function.

Edit - The file is still name global_variables.py as I didn't want to change it's name.

**Comment by amanabt** [comment]
@Balavarun5
 
I think that you have conceptual issues here.

First,
Reply to the comment
```
A variable initialized using the `global` keyword can be accessed anywhere within the code
(eg : A new function declared elsewhere in the module can use these variables.).
```
Inside a module, a global variable can be accessed throughout the module, by any function, irrespective of the fact whether it is being initialised using the `global` keyword or not.

Second,
Reply to the comment
```
The new implementation is to declare these variables in the module itself without the help of a function.
These variables can't be referenced inside a function elsewhere (i.e.- A new function declared elsewhere in the module cannot use these variables).
```
I don't know whether you know the difference between `declaring` a variable and `defining` a variable. Unlike C, C++, and JAVA, there is no concept of declaring a variable in Python. You always **define** a variable in python. Any function belonging to a module can always access all the global variables in that module.

**Comment by Balavarun5** [comment]
@amanabt 

take for instance a program:
```
test_variable = 5
def test_function():
    test_variable = 6
    return

test_function()
print(test_variable)
```
`test_variable` retains the value `5`

Now the same using global variables:
```
global test_variable
test_variable = 5
def test_function():
    global test_variable
    test_variable = 6
    return

test_function()
print(test_variable)
```
`test variable` now has value `6`
The approach we have been using is the second one. In my implementation I used the first approach. 

I don't have a great deal of knowledge about **defining** variables in python. But I think it's a good practice not to declare the variables using `global`.

@mchandra , thoughts?

**Comment by mchandra** [comment]
@Balavarun5 @amanabt 

Here is my understanding of global variables: *any* variables outside local scope are global variables. So for example:

```
test_variable = 5
def test_function():
    test_variable = 6
    return
```
In the above case, there is a variable in the global scope called `test_variable` and another variable with the *same* name in local scope named `test_variable`. This is bad code: Inside the function the value used will be that of the local `test_variable` and outside it will be the global `test_variable`. We should *not* have any variables outside local scope.

The following code is even worse than the above code:
```
global test_variable
test_variable = 5
def test_function():
    global test_variable
    test_variable = 6
    return
```

In this case, a function modifies a variable in the global scope! WHO HERE THOUGHT THAT THIS WAS A GOOD IDEA?!?

Please completely scrub the code of any variables outside local scope.

**Comment by amanabt** [comment]
@mchandra 
We wrote similar code to this
```
global test_variable
test_variable = 5
def test_function():
    global test_variable
    test_variable = 6
    return
```
in the earlier revisions, because we wanted to initialize the global variables depending on the values of
`N_LGL` and `number_of_elements` from `main.py`. At that time we were using a function `populateGlobalVariables` to do this, which belonged to the module `global_variables.py`, and to modify the global variables by a function defined inside the module `global_variables.py`, we had to use the `global` keyword.

If I understand it correctly, you are asking us to remove use of any global variables at all the places in the code, which means removing the file`global_variables.py`, right?

**Edit**
- Changed `main` to `main.py`

**Comment by Balavarun5** [comment]
@mchandra  @amanabt 
I am not using the variables outside the local scope inside any of the functions (i.e.- I'm not using the same name twice) in the code.

There are initial parameters like N_LGL, N_Elements which are defined outside the local scope.
Variables like lobatto_weights which will be used in other modules are obtained by running the functions and storing the value in a global scope.

I understand that any variable declared outside the local scope is a global variable and hence my claim that the revised code was free of global variables is wrong.

**Comment by mchandra** [comment]
Remove `global_variables.py`

**Comment by Balavarun5** [comment]
`global_variables.py` has been removed from the code
