### ISSUE TITLE
Mesh grid for 2D wave equation solver.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#21]
We are trying to get the solution of the 2D wave equation in an arbitrarily shaped domain, where, the domain is divided into `2^{nd}` order quadrangular mesh. During the initial development of the code, should we develop the code for solving arbitrarily shaped meshes, this will mean that we will need to integrate a mesh parsing software in our code (which we have already written), but we will do our initial testing for simple domains like a square?
Or, first, should we just hard code a mesh for a simple domain in the program and proceed with that?

**Comment by mchandra** [comment]
This sounds very convoluted:
```
During the initial development of the code, should we develop the code for solving arbitrarily shaped meshes, this will mean that we will need to integrate a mesh parsing software in our code (which we have already written), but we will do our initial testing for simple domains like a square?
```

Just code for a simple rectangular domain. Do NOT do arbitrary meshes at this time.
