### ISSUE TITLE
README.md edits.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#4]
**Commit Hash:** 0011aaf4f411560c378de7105c1d97bbfd126e4e

**Edits:**
- Add [tqdm](https://pypi.python.org/pypi/tqdm) in the `Dependencies` section.
- Add [pytest](https://docs.pytest.org/en/latest/) in the `Dependencies` section.
- Add a section explaining how to get the results from the DG_Maxwell code stating:
  - How to change the parameters for the simulations.
  - Where the does the result (which are right now in the form of images) gets stored.
  - How to create a video from the images.

**Comment by Balavarun5** [comment]
edited the readme.md with suggested changes in Balavarun5/DG_Maxwell .

**Comment by amanabt** [comment]
**Commit Hash:** 2008c0b0a23b3926cf6f33d88fa847924a51e8ca

* Instead of giving the heading `Note for users` name it `Usage`.
* Just look at the third line in which you are giving the code for generating video using `ffmpeg`, looks
  very dirty. You know that the README.md is parsed using `github markdown`, didn't you see the preview
  before pushing it. It should look like this.
`ffmpeg -f image2 -i %04d.png -vcodec mpeg4 -mbd rd -trellis 2 -cmp 2 -g
300 -pass 1 -r 25 -b 18000000 movie.mp4`

**Comment by amanabt** [comment]
@Balavarun5 
If you are making some comment about some changes which you have committed, please always add
a commit hash.

A commit hash is the UUID assigned to every commit we make on github. Just copy and paste the commit
hash whenever you are referring to some commit.

**Comment by Balavarun5** [comment]
@amanabt , There is already a section titled Usage: , do we merge it?

**Comment by amanabt** [comment]
@Balavarun5 
Yeah merge it.

**Comment by Balavarun5** [comment]
https://github.com/Balavarun5/DG_Maxwell/commit/549e024f1fdd744cc812fa4ea067951e1f6134e2
- Edited readme.md

**Comment by Balavarun5** [comment]
Suggested changes implemented, However the Readme.md needs to be updated to match company guidelines. Ref- #22
