### ISSUE TITLE
Iteration rate decreases on increasing the number of time steps.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#5]
**Commit Hash:** 756c8f6eeb4916c6d0f408c0b8793c7e6f684d24

Currently, the DG_Maxwell code is storing the time evolution of the wave in an
arrayfire array of dimension [N_LGL, N_element, N_time_steps]. On increasing the
number of time steps, the size of the array becomes very big and the speed of the
iteration decreases.

I am running the simulation on an Nvidia 820M GPU with a backend CUDA.

**Comment by amanabt** [comment]
One solution would be to create a list which will store the arrayfire array of dimension
[N_LGL, N_elements]. Then which the time evolution iteration, if we want to store the
particular time evolution, we can just append it to the list.

I think that the code is going slower because, with increasing number of time steps, the size
of the array that the GPU has to handle is very large. If we use the above solution then the
GPU will have to handle only [N_LGL, N_elements] sized array and hence it will make the
code faster.

**Comment by amanabt** [comment]
Another solution would be to use `hdf5` format to store `u_i` calculated at an iteration of time evolution, 
which will be an arrayfire array of dimension [N_LGL, N_elements], we can choose which of the `u_i` we
want to store and which one to leave.

**Comment by amanabt** [comment]
The problem with implementing using lists is that when it starts the program runs very fast but as the
size of the list becomes large the program becomes slower.
@Balavarun5 did this implementation and ran it and the program crashed after `14000^{th}` iteration.

**Comment by Balavarun5** [comment]
This issue has been fixed - 8759c941efa27720fb44f7efafe16182b6fc9f72
The iteration rate is now independent of the number of timesteps, however it still depends on the resolution of the simulation
