### ISSUE TITLE
Wave amplitude blowing up for large `t_total`. 

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#6]
**Commit Hash:** 756c8f6eeb4916c6d0f408c0b8793c7e6f684d24

**Issue:**
- The amplitude of the wave is steadily increasing with time and after a certain time
  it starts increasing exponentially.
- The figure below shows the amplitude vs time graph for `c_lax = 0` 
![image](https://user-images.githubusercontent.com/14011262/29248294-28bd4728-8032-11e7-95c3-443252bf047c.png)

- We have seen that the issue doesn't seem to depend on the value of `c_lax`. For this we compared
  the `Amplitude vs Time` graph `c_lax = c` and `c_lax = -c` and we got an overlapping graph as shown
  in the figure below.

![image](https://user-images.githubusercontent.com/14011262/29248307-84a07c18-8032-11e7-91d8-9f93d5a3d172.png)

**Expected Behaviour:** We expect the amplitude to decrease over time.

**Comment by Balavarun5** [comment]
This Issue has been fixed - 8759c941efa27720fb44f7efafe16182b6fc9f72
The wave is stable when evolved for reasonably large `t`. 
(eg: L1 norm after one full advection for courant = 0.25, N_LGL = 8, N_Elements = 10 is of the order of 1e-7)
