### ISSUE TITLE
Unresolved conflict section present in the code

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#68]
**Commit:** 4145945c8aa2644dd9103f18fe8f2b31a373d744

In the `test_utils` module, [line 142](https://github.com/Balavarun5/DG_Maxwell/blob/4145945c8aa2644dd9103f18fe8f2b31a373d744/dg_maxwell/tests/utils/test_utils.py#L142
) the conflict tag is still present. This is one of the causes of unit tests to fail.

Resolve the conflict.

**Comment by Balavarun5** [comment]
Resolved in 5c71deba7742ef079cadf45512c9984bf769c695
