### ISSUE TITLE
Implementation needed to plot hdf5 files.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/DG_Maxwell#7]
**Commit Hash:** 2008c0b0a23b3926cf6f33d88fa847924a51e8ca

**New Feature:** Implementation for plotting the simulation from the `hdf5` files are to be implemented.

**Comment by Balavarun5** [comment]
This issue has been fixed - 8759c941efa27720fb44f7efafe16182b6fc9f72
A post_proceesing.py file has been added. This, when run will plot the data stored in h5py files and subsequently make a movie out of the images.
